#===================================================================================================
# ABOUT THIS MACRO
# Description: Definition of source - its type, shape, position, activity, etc.
# Author: Mateusz Bała
# E-mail: bala.mateusz@gmail.com
#===================================================================================================

#==========================================================================================
# Definition of point source
# Source below is point at position (0,0,0) cm with activity 1 kBq. Mode of this source is
# JPETSource which offers three types of source: SGJPET (single gamma), pPsJPET (2 gammas
# from pPs decay) and oPsJPET (3 gammas from oPs decay). Here we use pPsJPEt type.
# These gammas momementum direction has spherical uniform distribution
#==========================================================================================

/gate/source/addSource PointSource JPETSource
/gate/source/PointSource/gps/type Point
/gate/source/PointSource/gps/pos/centre 0 0 0 cm
/gate/source/PointSource/setActivity 1 kBq
/gate/source/PointSource/setType pPsJPET
/gate/source/PointSource/setUseUnpolarizedParticles FALSE
/gate/source/PointSource/gps/particle gamma

# This options control distribution of gammas momentum directions
/gate/source/PointSource/gps/angtype iso
/gate/source/PointSource/gps/mintheta 0. deg
/gate/source/PointSource/gps/maxtheta 180. deg
/gate/source/PointSource/gps/minphi 0. deg
/gate/source/PointSource/gps/maxphi 360. deg

#===================================================================================================
# Definition of point source
# Source below is linear (cylinder shape) with center at position (0,0,0) cm, radiu 0.1 mm, 
# legth 50 cm and activity 1 kBq. 
# Model of this source is JPETSource which offers three types of source: 
# SGJPET (single gamma), pPsJPET (2 gammas from pPs decay) and oPsJPET (3 gammas from oPs decay). 
# Here we use oPsJPEt type.These gammas momementum direction has spherical uniform distribution
#===================================================================================================

/gate/source/addSource LinearSource JPETSource
/gate/source/LinearSource/gps/type Volume
/gate/source/LinearSource/gps/shape Cylinder
/gate/source/LinearSource/gps/radius 0.1 mm
/gate/source/LinearSource/gps/halfz 25 cm #Because cylinder length along z axis is 50, so halfz = 25
/gate/source/LinearSource/gps/pos/centre 0 0 0 cm
/gate/source/LinearSource/setActivity 1 kBq
/gate/source/LinearSource/setType oPsJPET
/gate/source/LinearSource/setUseUnpolarizedParticles FALSE
/gate/source/LinearSource/setLinearPolarizationAngle 0.0 deg
/gate/source/LinearSource/gps/particle gamma

# This options control distribution of gammas momentum directions
/gate/source/LinearSource/gps/angtype iso
/gate/source/LinearSource/gps/mintheta 0. deg
/gate/source/LinearSource/gps/maxtheta 180. deg
/gate/source/LinearSource/gps/minphi 0. deg
/gate/source/LinearSource/gps/maxphi 360. deg


#===================================================================================================
# Initialisation of sources
#===================================================================================================

/gate/source/list
