/**
 *  @copyright Copyright 2019 The J-PET Framework Authors. All rights reserved.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may find a copy of the License in the LICENCE file.
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  @file GateGlobalActorDictionaryEnums.hh
 */

#ifndef GateGlobalActorDictionaryEnums_hh
#define GateGlobalActorDictionaryEnums_hh
#include <TObject.h>

/**
 * @About class: This class contains definitios enums required to work with events generated by JPET sources.
 * @author: Mateusz Bała
 * @email: bala.mateusz@gmail.com
 */
class GateGlobalActorDictionaryEnums: public TObject {
public:
  GateGlobalActorDictionaryEnums();

  //Which model has been used to generate event
  enum GammaSourceModel
  {
   Unknown = 0, //default value
   Single = 1, //event is generated by class GateJPETSingleGammaModel ( macro model name is SGJPET )
   ParaPositronium = 2, //event is generated by class GateJPETParaPositroniumDecayModel ( pPsJPET )
   OrthoPositronium = 3, //event is generated by class GateJPETOrtoPositroniumDecayModel ( oPsJPET )
   ParaPositroniumAndPrompt = 4, //event is generated by class GateJPETParaPlusPromptDecayModel ( pPsAndPromptJPET )
   OrthoPositroniumAndPrompt = 5, //event is generated by class GateJPETOrtoPlusPromptDecayModel ( oPsAndPromptJPET )
   Other = 6 // event is generated by one of this classes: GateJPETFourGammasDecayModel ( FourGammasJPET ) or GateJPETFiveGammasDecayModel ( FiveGammasJPET )
  };

  static GammaSourceModel getGammaSourceModel( const int& value );

  //What kind of gamma is in a track
  enum GammaKind
  {
   GammaUnknown = 0, //defalut value
   GammaSingle = 1, //single gamma which is not the prompt gamma
   GammaPrompt = 2, //single gamma which is the prompt gamma
   GammaFromParaPositronium = 3, //gamma is produced by pPs decay
   GammaFromOrthoPositronium = 4, //gamma is produced by oPs decay
   GammaFromOtherModel = 5 //other models
  };

  static GammaKind getGammaKind( const int& value );

  //In case of merging hits this enum indicates this modification of hit
  enum HitKind
  {
   HitUnknown = 0, //default value
   HitNotMerged = 1, //not merged hit - in this case hit has the same data as was in the track from G4Step
   HitMerged = 2 //merged hit - more than two hits were merged to one new hit
  };

  static HitKind getHitKind( const int& value );

  ClassDef(GateGlobalActorDictionaryEnums,1)
};
#endif /*  !GateGlobalActorEnums_hh */
