/gate/actor/addActor LocalActor JPActor
/gate/actor/JPActor/attachTo crystal1

/gate/actor/addActor LocalActor JPActor2
/gate/actor/JPActor2/attachTo crystal2

/gate/actor/addActor LocalActor JPActor3
/gate/actor/JPActor3/attachTo crystal3

/gate/actor/JPActor/global/saveTo results_nema.root
/gate/actor/JPActor/global/enableEventID
/gate/actor/JPActor/global/enableTrackID
/gate/actor/JPActor/global/enableProcessPosition
/gate/actor/JPActor/global/filterParticleName gamma
/gate/actor/JPActor/global/filterProcessName Compton
/gate/actor/JPActor/global/enableEmissionPointFromSource
/gate/actor/JPActor/global/enableEnergyBeforeProcess
/gate/actor/JPActor/global/enableEnergyLossDuringProcess
/gate/actor/JPActor/global/enableVolumeName
/gate/actor/JPActor/global/enableScintilatorPosition
/gate/actor/JPActor/global/enableEmissionPointFromSource

